name: Build and Publish to Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@master
      with:
        root_file: uwapcs_constitution.tex
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master-build
        publish_dir: ./
