name: Test Build

on: [push, pull_request]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@master
      with:
        root_file: uwapcs_constitution.tex
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: result
        path: ./
